38 display donor
oss-slu/material-donor-mutual-assist pull request #63
Opened 2024-10-28 19:57 UTC by truffer11

# Pull Request Template

**Fixes #38 **

### What was changed?

- Adds a new donor page where you can see a list of all donors
- DonatedItemsList.js was updated to .tsx
- Enums.js was updated to .tsx
- Added "All Donors" section under Donors dropdown in navbar

### Why was it changed?

- The .js files were updated to .tsx to add additional security, as part of our ongoing project of updating old js code to tsx
- The donor page allows for administration to find donors easily and get details on each donor

### How was it changed?

- Utilized the .tsx code from DonatedItemsList to ensure we kept the same look across the website
- Currently, there are five columns for the donors: Donor ID, First Name, Last Name, email, and more details. More details is where you will be able to get more specifics including address and stuff. This was done to make the list more readable, while still giving enough information to verify you are looking at the right donor.

### Screenshots that show the changes (if applicable):

- **After:**
  - ![Screenshot 2024-10-28 145622](https://github.com/user-attachments/assets/e500d37e-9db8-49c3-a0e9-7327f9691538)

2024-10-28 22:36 UTC, miabu-pashh commented on client-app/src/Components/DonatedItemsList.tsx
I have worked on this file change, you can revert the files changes in this file.

2024-10-28 22:37 UTC, miabu-pashh commented on client-app/src/Components/Navbar.tsx
> +                                            <Link className="dropdown-item" to="/donorlist">All Donors</Link>
reduce the comments and try to edit the existing link.

2024-10-28 22:39 UTC, miabu-pashh commented on client-app/src/constants/Enums.ts
I guess Enums file change is not necessary for your issue.

2024-10-28 22:43 UTC, miabu-pashh commented on client-app/src/Components/DonorList.tsx
the table is touching the top navbar.  create a css file for this list component and update the styles.

2024-10-28 22:46 UTC, miabu-pashh reviewed
1. Some files needs to be reverted, as it was done by other team members for the same team sprint.
2. need to add css
3. minimize the comments lines
4. run the prettier check before the pull request.

2024-10-30 20:10 UTC, Anjali0407-git requested changes

2024-10-30 20:10 UTC, Anjali0407-git commented on client-app/src/Components/DonorList.tsx
> +                    <button onClick={() => handleAddNewDonationClick()}>
Function name should be relevant to Donors, please change it

2024-10-30 20:10 UTC, Anjali0407-git commented on client-app/src/Components/DonorList.tsx
> +                                {assignProgramClicked && (
I see that you added `assignProgramClicked` in couple of places in this page. What is this for?

2024-11-04 16:33 UTC, Anjali0407-git commented
@truffer11 Is this ready for re-review?

2024-11-04 20:38 UTC, Anjali0407-git commented on client-app/src/Components/DonorList.tsx
> +                    //`${process.env.REACT_APP_BACKEND_API_BASE_URL}/donor`
@truffer11 Please replace the hardcoded data with environment variables

2024-11-04 20:39 UTC, Anjali0407-git commented on client-app/src/Components/DonorList.tsx
> +            <Modal isOpen={modalIsOpen} onRequestClose={() => setModalIsOpen(false)}>
@truffer11 Please remove this modal. We do not need donor details in program page

2024-11-04 20:54 UTC, Anjali0407-git commented on client-app/src/Components/DonorListTest.jsx
> +describe('DonorList Component', () => {
@truffer11 we have seperate tests folder for writing tests, can you please move this test suite to there? also ensure you follow the same file naming convention .

2024-11-04 20:54 UTC, Anjali0407-git commented on client-app/src/Components/DonorListTest.jsx
> +describe('DonorList Component', () => {
Also there are merge conflicts

2024-11-04 20:55 UTC, Anjali0407-git commented on server/src/views/error.jade
> +    title Error
@truffer11 remove this file please

2024-11-04 21:26 UTC, Anjali0407-git commented
All changes looks god, but merge conflicts??...

2024-11-04 21:46 UTC, merged