#64 Enhance GET /donatedItem to retrive and send images directly to frontend
oss-slu/material-donor-mutual-assist pull request #70
Opened 2024-11-10 05:36 UTC by saikiran0405

**Fixes #64 **

### What was changed?

- Update the donations page to display images based on each status.

### Why was it changed?

- This change was made to simplify the client-side logic by handling all cloud storage communications on the server side. Now, the client receives and displays images directly, eliminating the need for additional processing or API calls to retrieve image data.

### How was it changed?
The GET `/donatedItem` endpoint was modified to include logic for fetching image data directly from cloud storage URLs associated with each donated item's status, converting this data to Base64 strings, and embedding these images in the response payload. This was implemented primarily in the `fetchImagesFromCloud` and `streamToBase64` utility functions.

### Screenshots that show the changes (if applicable):

- **Before:**
 
![Sprint_5_1](https://github.com/user-attachments/assets/4c37bb21-be2d-4788-a7f9-6d35e2420714)

- **After:**
![Sprint_5](https://github.com/user-attachments/assets/44b28e0e-6655-4aba-8b9e-a757809f7312)

2024-11-12 00:00 UTC, truffer11 requested changes
Apart from the fact that we couldn't get it working on my machine, this looks really good!

2024-11-12 00:00 UTC, truffer11 commented on client-app/src/Components/DonatedItemDetails.tsx
> +                                    <img key={index} src={`data:image/jpeg;base64,${image}`} alt={`Status Image ${index}`} style={{ width: '100px', height: '100px', margin: '5px' }} />
I would consider allowing for additional format options. The instructions for the upload state that the user can post JPG or PNG files.

2024-11-14 03:59 UTC, Anjali0407-git commented on server/src/services/donatedItemService.ts
> +export const fetchImagesFromCloud = async (imageUrls: string[]) => {
I assume its because of not having a container named `'mdma-dev'` created in your azure storage

2024-11-14 04:04 UTC, Anjali0407-git requested changes

2024-11-14 04:04 UTC, Anjali0407-git commented on server/src/services/donatedItemService.ts
> +        console.log(base64Image);
please remove this log as it would print a very long image string

2024-11-14 04:04 UTC, Anjali0407-git commented on server/src/services/donatedItemService.ts
> +        const base64Image = await streamToBase64(stream);
This function is well written, well done!!

2024-11-14 04:04 UTC, Anjali0407-git commented on client-app/src/Components/DonatedItemDetails.tsx
> +                                    <img key={index} src={`data:image/jpeg;base64,${image}`} alt={`Status Image ${index}`} style={{ width: '100px', height: '100px', margin: '5px' }} />
Can you move these styles to css file to keep things organized. Also increase the image size by 1.5x, its too small now

2024-11-17 17:50 UTC, Anjali0407-git approved these changes

2024-11-17 17:50 UTC, merged