Issue66
oss-slu/material-donor-mutual-assist pull request #71
Opened 2024-11-11 06:44 UTC by miabu-pashh

Fixes #66 

### What was changed?

- Enhanced the PUT /donatedItem/status/:id endpoint to handle the uploading of image files.

- Modified the endpoint to:

- Accept imageFiles  in a multipart file format.

- Upload image files to cloud storage and generate unique URLs.

- Update the donatedItemStatus table with the statusType, dateModified, and imageUrls.

- Added error handling for validation, file uploads, and database updates.

### Why was it changed?

- Previously, the PUT /donatedItem/status/:id endpoint lacked the capability to handle image file uploads.

- The enhancement was needed to allow users to upload images associated with a status update and store their URLs for future reference.

- This improvement ensures a better user experience and provides more flexibility for managing donated items and their statuses.

### How was it changed?

- Updated the endpoint logic in the donatedItemRoutes.ts file:

- Added upload.array('imageFiles') middleware to process multipart file uploads.

- Integrated the uploadToStorage function to upload image files to cloud storage and generate unique filenames.

- Used prisma.donatedItemStatus.update() to update the status record in the database with the new details and image URLs.

- Refactored validation to ensure statusType and dateModified are mandatory fields.

### Screenshots that show the changes (if applicable):
Postman Success Message:
Before:

The endpoint did not support image uploads and returned an error if images were included.
After:
Successfully updated the donatedItemStatus with image URLs:

<img width="1470" alt="Screenshot 2024-11-11 at 12 22 01 AM" src="https://github.com/user-attachments/assets/41208585-e713-4166-bb27-8cd1ffba6466">

2024-11-11 23:57 UTC, saikiran0405 commented on server/src/routes/donatedItemRoutes.ts
> +                    .json({ error: 'statusType and dateModified are required' });
Enhance validation for statusType and dateModified to check for valid formats or values.

2024-11-11 23:57 UTC, saikiran0405 commented on server/src/routes/donatedItemRoutes.ts
> +            // Upload images to cloud storage and retrieve URLs
Ensure there's a check for imageFiles being undefined or empty before processing uploads.

2024-11-11 23:59 UTC, saikiran0405 commented on server/src/routes/donatedItemRoutes.ts
> +                    message: 'Error updating donated item status',
Consider refining error handling to address specific exceptions more comprehensively

2024-11-12 00:02 UTC, saikiran0405 reviewed
1. In the code review for the `PUT /donatedItem/status/:id` endpoint, I have addressed enhancements in error handling, input validation, and date processing. 

2. Recommendations included refining error management, improving the validation of input parameters for accuracy, and revising the approach to date normalization. 

3. Additionally, suggested implementing safeguards against potential file handling errors

2024-11-14 03:16 UTC, Anjali0407-git requested changes

2024-11-14 03:16 UTC, Anjali0407-git commented on server/src/routes/donatedItemStatusRoutes.ts
> +            const imageUrls = await Promise.all(
Does it works even when imageFiles is sent as null?

2024-11-14 03:16 UTC, Anjali0407-git commented on server/src/routes/donatedItemStatusRoutes.ts
> +                },
Already prisma create and update methods are in place [as shown ](https://github.com/oss-slu/material-donor-mutual-assist/blob/main/server/src/routes/donatedItemStatusRoutes.ts#L16C12-L33C16). Just adding `imageUrls `to .update method would work.

2024-11-14 16:58 UTC, miabu-pashh commented
![image](https://github.com/user-attachments/assets/86d24623-daea-49e3-8215-f88054897ff8)

2024-11-17 17:47 UTC, Anjali0407-git approved these changes

2024-11-17 17:48 UTC, merged