Fix #76: Enhance Clickable Area and Hover Responsiveness in Donations Table
oss-slu/material-donor-mutual-assist pull request #93
Opened 2024-11-26 02:18 UTC by Gayatrinj

**Fixes #76 **

### What was changed?

- Enhanced the donations table to make entire rows clickable instead of just the item ID.
- Added hover effects to improve interactivity and user experience.
- Prevented undesired row navigation when interacting with certain elements (e.g., checkboxes and buttons).
- Added CSS to implement hover effects.
- Implemented test cases to validate the hover functionality and clickable row behavior.

### Why was it changed?

- Previously, only the item ID was clickable, leading to a poor user experience.
- Making rows clickable provides a more intuitive and user-friendly interface.
- Hover effects visually indicate that rows are interactive, improving usability.
- Test cases ensure reliability and avoid regressions in future updates.

### How was it changed?

- **Script Changes**:
  Added an onClick event listener to <tr> elements to navigate to the donation details page when rows are clicked:
```
onClick={() => navigate(`/donations/${item.id}`)}
```

- **Used stopPropagation for buttons and checkboxes to prevent triggering the row click event:
```
e.stopPropagation();

```
**CSS changes**:

- Added hover effects for rows using the _.clickable-row_ class

### Screenshots that show the changes:

- **Before:**

- Only the item ID was clickable.
- No hover effect to indicate interactivity.
-
![before](https://github.com/user-attachments/assets/33f8976c-9b82-401b-9219-eb84ec859e68)

- **After:**

Entire row is clickable.
Added hover effect to rows for better feedback.

![now](https://github.com/user-attachments/assets/581229fd-2a7b-4769-8c49-c4090b1cdd7a)

2024-11-27 23:41 UTC, Anjali0407-git commented
Changes looks good. 

Please address the following changes before merging this PR:

1. There were some latest changes in the upstream branch, can you please pull them and fix merge conflicts if any?
2. It seems you did not run the prettier check on your code. Please follow this documentation to ensure prettier checks are passed https://github.com/oss-slu/material-donor-mutual-assist/blob/main/README.md#code-formatting

2024-11-27 23:43 UTC, Anjali0407-git requested changes

2024-11-27 23:43 UTC, Anjali0407-git commented on client-app/src/Components/DonatedItemsList.tsx
> +        <tr>
It seems these are the trivial changes with some indentation removed. Prettier should apply the formatting updates to your code. Please run prettier write on your code

2024-11-27 23:49 UTC, Anjali0407-git commented
You can see in github actions that Prettier check pipeline failed 
https://github.com/oss-slu/material-donor-mutual-assist/actions

2024-11-28 01:36 UTC, Gayatrinj commented
I have completed all the requested changes:

- Merged the latest changes from the main branch and resolved any conflicts.
- Verified and formatted the code using Prettier (prettier:write and prettier:check).

2024-11-28 18:08 UTC, Anjali0407-git requested changes

2024-11-28 18:08 UTC, Anjali0407-git commented on client-app/package.json
> -  "name": "my-app",
@Gayatrinj `package.json` and `package-lock.json` file should not auto formatted by prettier as you can see [here ](https://github.com/oss-slu/material-donor-mutual-assist/blob/main/.prettierignore)that these files are ignored by prettier. Please do not push any trivial changes to `package.json` and `package-lock.json` file unless you have some new dependency added to it.

2024-11-28 18:08 UTC, Anjali0407-git commented on client-app/.babelrc
> -}
@Gayatrinj Please revert the changes to this file. I would suggest to not push any trivial changes.

2024-11-28 18:08 UTC, Anjali0407-git commented on client-app/package.json
> -  "name": "my-app",
Please revert changes to both of these files and push only if you have any new dependency added

2024-11-28 18:18 UTC, Anjali0407-git requested changes

2024-11-28 18:18 UTC, Anjali0407-git commented on client-app/src/Components/Register.js
> -
Can you also check why others changes are appearing in your PR? As you have already merged the upstream main branch into your working branch, these changes of others are not supposed to be shown here.

2024-11-28 20:16 UTC, closed without merging